# Generated by Django 4.0.2 on 2022-02-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_client', '0002_mention_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='level',
            field=models.IntegerField(),
        ),
    ]
