# Generated by Django 4.0.2 on 2022-02-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_client', '0004_music_artist_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('access_key', models.CharField(max_length=400)),
                ('access_secret', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'authkey',
            },
        ),
    ]
